# Generated by Django 5.0 on 2023-12-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='expiration_date',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='organization',
            field=models.CharField(max_length=255),
        ),
    ]
