# Generated by Django 5.0 on 2023-12-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_certificate_expiration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='issue_date',
        ),
    ]
